### Create a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

### Get all users
GET http://localhost:3003/api/users